#pragma once

#include "NativeGameplayTags.h"

namespace AuraPrimaryAttributeTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Strength)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Intelligence)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Resilience)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary_Vigor)
}

namespace AuraSecondaryAttributeTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_Armor)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_ArmorPenetration)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_BlockChance)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalHitChance)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalHitDamage)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_CriticalHitResistance)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_HealthRegeneration)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_ManaRegeneration)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_MaxHealth)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Secondary_MaxMana)
}

namespace AuraInputTag
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LMB)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_RMB)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_1)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_2)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_3)
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_4)
}